export const teachers = {
    1: 'Rut Cohen',
    2: 'Hana Levy',
    3: 'Rav Zhuker',
    4: 'Rachel Karlibach',
    5: 'Rut Elshtein',
    6: 'Michal Yutkovski',
    7: 'Brooroa Goldvaser',
    8: 'Chana Toib',
    9: 'Miriam Bichler',
    10: 'Mina Erenfeld',
    11: 'Rut Lifshizh',
    12: 'Malci Sofer',
    13: 'Rivka Volovzhic',
    14: 'Michal Berk',
    15: 'Dina Bachrach',
    16: 'Fraidi Miron',
    17: 'Ester Irshfeld',
    18: 'Efrat Shainer',
    19: 'Tova Miler',
    20: 'Chana Paley',
    21: 'Lea Drabkin',
    22: 'Ester Ariely',
    23: 'Dina Elfer',
    24: 'Chaya Shtemer',
    25: 'Dina Ofner'
  };
  
  export const subjects = {
    1: 'Tora',
    2: 'Math',
    3: 'Ashkafa',
    4: 'Grammer',
    5: 'English',
    6: 'Dinim',
    7: 'Syntax',
    8: 'Tora-a',
    9: 'Tora-b',
    10: 'History-Israeli',
    11: 'History-Public',
    12: 'Mishley',
    13: 'Education',
    14: 'Kitchen',
    15: 'Daniel',
    16: 'Expression',
    17: 'Yaadut',
    18: 'Gym',
    19: 'Navy',
    20: 'Ktuvim',
    21: 'Biology',
    22: 'Pyut'
  };
  